version: '3.1'
services:
  api:
    image: orionvmasmasfront
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - "orionappfront"
    ports:
      - "4200:4200"


networks:
  orionappfront: